---
- name: Setup MacOS
  hosts: localhost
  connection: local
  tasks:
    - name: Change default shell to bash
      command: chsh -s /bin/bash
      become: true
      become_user: "{{ ansible_user_id }}"
      when: ansible_user_shell != '/bin/bash'

    - name: Set scroll direction
      osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        type: bool
        value: false

    - name: Trackpad corner is secondary mouse click
      osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: TrackpadCornerSecondaryClick
        type: int
        value: 2

    - name: xQuartz dpi
      osx_defaults:
        domain: org.xquartz.X11
        key: dpi
        type: int
        value: 254

    - name: Enable trackpad right click
      osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: TrackpadRightClick
        type: bool
        value: true

    - name: Leave my desktops alone!
      osx_defaults:
        domain: "com.apple.dock"
        key: "mru-spaces"
        type: "bool"
        value: false
      notify: Restart Dock

    - name: "Dock - Persistent Apps"
      notify: Restart Dock
      osx_defaults:
        domain: "com.apple.dock"
        key: "persistent-apps"
        type: array
        value:
          - <dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Safari.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>
          - <dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Slack.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>

    - name: "Set Cursor files"
      file:
        state: link
        force: true
        src: "~/.config/cursor/{{ item }}"
        dest: "~/Library/Application Support/Cursor/User/{{ item }}"
      loop:
        - "settings.json"
        - "keybindings.json"

    - name: Enable Dark Mode
      osx_defaults:
        domain: NSGlobalDomain
        key: AppleInterfaceStyle
        type: string
        value: Dark

  handlers:
    - name: Restart Dock
      command: killall Dock
